-- ============================================================
-- ROLÊ — Conta, segurança e gestão de denúncias
-- Rode o arquivo inteiro no SQL Editor. Pode repetir sem quebrar.
-- ============================================================


-- ============================================================
-- 1. EXCLUSÃO DA PRÓPRIA CONTA
--
-- O navegador não pode apagar de auth.users: a chave anon não
-- tem esse poder, e é bom que não tenha. A saída é uma função
-- SECURITY DEFINER, que roda com os privilégios de quem a criou
-- mas só apaga a linha de quem chamou — auth.uid() não pode ser
-- forjado pelo cliente.
--
-- Como perfis referencia auth.users com ON DELETE CASCADE,
-- eventos, comentários, favoritos e interesses vão junto.
-- ============================================================
create or replace function public.excluir_minha_conta()
returns void
language plpgsql
security definer set search_path = public, auth
as $$
declare
  eu uuid := auth.uid();
begin
  if eu is null then
    raise exception 'Nenhuma sessão ativa';
  end if;

  delete from auth.users where id = eu;
end;
$$;

revoke all on function public.excluir_minha_conta() from public, anon;
grant execute on function public.excluir_minha_conta() to authenticated;


-- ============================================================
-- 2. ACEITE DAS REGRAS DE CONVIVÊNCIA
-- ============================================================
alter table public.perfis
  add column if not exists aceitou_regras     boolean not null default false,
  add column if not exists regras_aceitas_em  timestamptz;

create or replace function public.criar_perfil()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  aceite boolean := coalesce((new.raw_user_meta_data->>'aceitou_regras')::boolean, false);
begin
  insert into public.perfis (id, nome, email, data_nascimento, aceitou_regras, regras_aceitas_em)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nome', split_part(new.email,'@',1)),
    new.email,
    nullif(new.raw_user_meta_data->>'data_nascimento','')::date,
    aceite,
    case when aceite then now() end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;


-- ============================================================
-- 3. DENÚNCIAS: NÚMERO, STATUS E PRAZO
-- ============================================================

-- 3.1 número curto para o administrador citar ("denúncia 42")
alter table public.denuncias
  add column if not exists numero        bigint generated by default as identity,
  add column if not exists finalizada_em timestamptz,
  add column if not exists resposta      text;

create index if not exists denuncias_numero_idx on public.denuncias (numero);

-- 3.2 novos status
alter table public.denuncias drop constraint if exists denuncias_status_check;

update public.denuncias set status = 'recebida'   where status = 'aberta';
update public.denuncias set status = 'finalizada' where status = 'analisada';

alter table public.denuncias
  add constraint denuncias_status_check
  check (status in ('recebida','em_analise','finalizada','arquivada'));

alter table public.denuncias alter column status set default 'recebida';

-- quem denunciou passa a poder acompanhar a própria denúncia
drop policy if exists den_ler_proprias on public.denuncias;
create policy den_ler_proprias on public.denuncias
  for select using (auth.uid() = usuario_id);


-- ============================================================
-- 4. NOTIFICAÇÕES
-- ============================================================
create table if not exists public.notificacoes (
  id           uuid primary key default gen_random_uuid(),
  usuario_id   uuid not null references public.perfis(id) on delete cascade,
  titulo       text not null,
  mensagem     text not null,
  denuncia_id  uuid references public.denuncias(id) on delete cascade,
  lida         boolean not null default false,
  criado_em    timestamptz not null default now()
);

create index if not exists notificacoes_usuario_idx
  on public.notificacoes (usuario_id, lida, criado_em desc);

alter table public.notificacoes enable row level security;

-- cada um vê e marca como lida apenas as suas
drop policy if exists notif_ler on public.notificacoes;
create policy notif_ler on public.notificacoes
  for select using (auth.uid() = usuario_id);

drop policy if exists notif_marcar on public.notificacoes;
create policy notif_marcar on public.notificacoes
  for update using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);

drop policy if exists notif_apagar on public.notificacoes;
create policy notif_apagar on public.notificacoes
  for delete using (auth.uid() = usuario_id);


-- ------------------------------------------------------------
-- 4.1 Toda mudança de status avisa quem denunciou
-- O gatilho é SECURITY DEFINER porque quem muda o status é o
-- administrador, mas a notificação pertence a outra pessoa.
-- ------------------------------------------------------------
create or replace function public.notificar_status_denuncia()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  texto text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  if new.status = 'finalizada' then
    new.finalizada_em := now();
  elsif old.status = 'finalizada' then
    new.finalizada_em := null;        -- voltou atrás, o prazo reinicia
  end if;

  texto := case new.status
    when 'em_analise' then 'Sua denúncia está sendo analisada pela moderação.'
    when 'finalizada' then 'Sua denúncia foi analisada e finalizada. Obrigado por avisar.'
    when 'arquivada'  then 'Sua denúncia foi arquivada sem providências.'
    else 'Sua denúncia foi recebida e entrou na fila de análise.'
  end;

  if new.resposta is not null and length(trim(new.resposta)) > 0 then
    texto := texto || ' Resposta da moderação: ' || new.resposta;
  end if;

  if new.usuario_id is not null then
    insert into public.notificacoes (usuario_id, titulo, mensagem, denuncia_id)
    values (new.usuario_id, 'Denúncia nº ' || new.numero, texto, new.id);
  end if;

  return new;
end;
$$;

drop trigger if exists ao_mudar_status_denuncia on public.denuncias;
create trigger ao_mudar_status_denuncia
  before update on public.denuncias
  for each row execute function public.notificar_status_denuncia();


-- ============================================================
-- 5. LIMPEZA AUTOMÁTICA (7 dias após finalizar)
--
-- A função é chamada pelo painel sempre que o administrador
-- abre a área de denúncias. Se o seu projeto tiver pg_cron,
-- dá para agendar — o comando está comentado no fim.
-- ============================================================
create or replace function public.limpar_denuncias_antigas()
returns integer
language plpgsql
security definer set search_path = public
as $$
declare
  apagadas integer;
begin
  delete from public.denuncias
  where status = 'finalizada'
    and finalizada_em is not null
    and finalizada_em < now() - interval '7 days';

  get diagnostics apagadas = row_count;
  return apagadas;
end;
$$;

grant execute on function public.limpar_denuncias_antigas() to authenticated;

-- Opcional, se o pg_cron estiver disponível (Database > Extensions):
--   create extension if not exists pg_cron;
--   select cron.schedule('limpar-denuncias', '0 3 * * *',
--                        $$select public.limpar_denuncias_antigas()$$);


-- ============================================================
-- 6. VIEW DAS DENÚNCIAS
-- Traz nome de quem denunciou e do evento, para o painel poder
-- pesquisar por qualquer um deles numa consulta só.
-- ============================================================
drop view if exists public.denuncias_lista;

create view public.denuncias_lista
with (security_invoker = true) as
select
  d.id, d.numero, d.evento_id, d.usuario_id,
  d.motivo, d.descricao, d.status, d.resposta,
  d.criado_em, d.finalizada_em,
  e.nome  as evento_nome,
  e.ativo as evento_ativo,
  p.nome  as autor_nome,
  p.email as autor_email,
  case
    when d.status = 'finalizada' and d.finalizada_em is not null
    then greatest(0, 7 - extract(day from now() - d.finalizada_em)::int)
  end as dias_ate_remocao
from public.denuncias d
left join public.eventos e on e.id = d.evento_id
left join public.perfis  p on p.id = d.usuario_id;

grant select on public.denuncias_lista to authenticated;


-- ============================================================
-- 7. TEMPO REAL NAS NOTIFICAÇÕES (opcional)
-- ============================================================
do $$
begin
  alter publication supabase_realtime add table public.notificacoes;
exception when duplicate_object then
  null;
end
$$;


-- ============================================================
-- 8. CONFERÊNCIA
-- ============================================================
select numero, status, criado_em, finalizada_em
from public.denuncias
order by numero desc
limit 10;
